<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fu/usr/lib64/lazarus/packager/units/$(CPU_TARGET)-$(OS_TARGET);.  -MObjFPC -Scghi -O1 -g -gl -l -vewnhibq sm.pas"/>
</CONFIG>
